eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
  datasource:
     name: dev
     url: jdbc:mysql://127.0.0.1:3306/snailmall
     username: root
     password: root
redis:
    host: 127.0.0.1
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
zk:
  host: 127.0.0.1
